# Generated by Django 4.0.1 on 2022-01-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familiya', models.CharField(blank=True, max_length=255, null=True, verbose_name='Familiya')),
                ('ism', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ism')),
                ('sharf', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sharf')),
                ('kurs_kuni', models.DateField(blank=True, null=True, verbose_name="Kurs o'tagan vaqti")),
                ('cer_nomer', models.BigIntegerField(default=0, null=True, verbose_name='Sertifikat raqami')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
            ],
            options={
                'verbose_name': 'Sertifikat',
                'verbose_name_plural': 'Sertifikatlar',
            },
        ),
    ]
