# Generated by Django 4.0.1 on 2022-03-04 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Kurs nomi')),
                ('description', models.TextField(null=True, verbose_name='Text')),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familiya', models.CharField(blank=True, max_length=255, null=True, verbose_name='Familiya')),
                ('ism', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ism')),
                ('sharf', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sharf')),
                ('kurs_kuni', models.DateField(blank=True, null=True, verbose_name="Kurs o'tagan vaqti")),
                ('cer_nomer', models.BigIntegerField(default=0, null=True, verbose_name='Sertifikat raqami')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR Code')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificate.course')),
            ],
            options={
                'verbose_name': 'Sertifikat',
                'verbose_name_plural': 'Sertifikatlar',
            },
        ),
    ]
