# Generated by Django 4.0.1 on 2022-03-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='kurs_kuni',
        ),
        migrations.AddField(
            model_name='certificate',
            name='end_date',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Kurs tugagan kun'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='month',
            field=models.CharField(blank=True, choices=[('yanvar', 'Yanvar'), ('fevral', 'Fevral'), ('mart', 'Mart'), ('aprel', 'Aprel'), ('may', 'May'), ('iyun', 'Iyun'), ('iyul', 'Iyul'), ('avgust', 'Avgust'), ('sentabr', 'Sentabr'), ('oktabr', 'Oktabr'), ('dekabr', 'Dekabr')], default='yanvar', max_length=50, null=True, verbose_name='Oy'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='start_date',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Kurs boshlangan kun'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Kurs nomi'),
        ),
    ]
