# Generated by Django 4.0.1 on 2022-03-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0002_remove_certificate_kurs_kuni_certificate_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='qr_code',
            field=models.ImageField(default='qe.png', upload_to='qr_codes/', verbose_name='QR Code'),
        ),
    ]
