# Generated by Django 4.0.1 on 2022-03-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0003_alter_certificate_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='sharf',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Sharf'),
        ),
    ]
